# Generated by Django 5.2 on 2025-06-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('suporte_email', models.EmailField(max_length=254, verbose_name='E-mail de Suporte')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('site_titulo', models.CharField(max_length=100, verbose_name='Título do Site')),
                ('chave_pix', models.CharField(max_length=100, verbose_name='Chave PIX')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
