# Generated by Django 5.2 on 2025-06-24 15:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfigcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hero_slider', 'Hero Slider (Home)'), ('logo_pequena', 'Logo Pequena'), ('logo_grande', 'Logo Grande'), ('galeria', 'Galeria (Home)'), ('topo_sobre', 'Imagem no Topo (Sobre)'), ('meio_sobre', 'Imagem no Meio (Sobre)'), ('topo_contato', 'Imagem no Topo (Contato)'), ('topo_noticia', 'Imagem no Topo (Notícia)'), ('sem_noticia', 'Imagem Padrão (Sem Notícia)')], help_text='Selecione onde esta imagem será utilizada', max_length=30)),
                ('imagem', models.ImageField(help_text='Formatos aceitos: JPG, PNG, WebP', upload_to=core.models.upload_imagem_site)),
                ('titulo', models.CharField(blank=True, help_text='Título da imagem (usado em alt text)', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada para acessibilidade')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para acessibilidade (se vazio, usará o título)', max_length=200)),
                ('ativo', models.BooleanField(default=True, help_text='Marque para exibir esta imagem no site')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)')),
                ('tamanho_arquivo', models.PositiveIntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagem do Site',
                'verbose_name_plural': 'Imagens do Site',
                'ordering': ['tipo', 'ordem', '-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='core_imagem_tipo_d99cec_idx'), models.Index(fields=['ordem'], name='core_imagem_ordem_938574_idx')],
            },
        ),
    ]
