# Generated by Django 5.2 on 2025-04-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='endereco',
        ),
        migrations.AddField(
            model_name='membro',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membro',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='membro',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membro',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membro',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='membro',
            name='disponivel_voluntario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membro',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='membro',
            name='interesses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membro',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='membro',
            name='receber_notificacoes',
            field=models.BooleanField(default=True),
        ),
    ]
