# Generated by Django 5.2 on 2025-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_resumo_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('noticia', 'Notícia'), ('evento', 'Evento')], default='noticia', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='local_evento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
