# Generated by Django 5.2 on 2025-05-01 23:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_categoria_noticia_data_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
