# Generated by Django 5.2 on 2025-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
