"""
Django settings for amuvsite project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import locale

try:
    locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')
except locale.Error:
    # Fallback: usa o padrão do sistema
    locale.setlocale(locale.LC_TIME, '')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY não definida! Configure no .env ou no ambiente.")


ALLOWED_HOSTS = [host.strip() for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost").split(",")]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'widget_tweaks',

    # Allauth (ordem é importante!)
    'django.contrib.sites',  # necessário para o allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # opcional, mas recomendado

    # Seus apps
    'core',
    'noticias',
    'membros',

    # App de cores
    'colorfield',

    # CkEditor editor para noticias
    'ckeditor',
    'ckeditor_uploader',  # Para upload de imagens
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middleware do allauth
    'allauth.account.middleware.AccountMiddleware',

    'core.middleware.SiteConfigMiddleware',
]

ROOT_URLCONF = 'amuvsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'noticias.context_processors.common_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'amuvsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CKEDITOR_UPLOAD_PATH = 'uploads/'

# Configurações opcionais para personalizar o CKEditor
CKEDITOR_CONFIGS = {
    'default': {
        #'removePlugins': 'preview,openlink',
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['Link', 'Unlink'],
            ['Image', 'Table'],
            ['Source', 'Maximize', 'RemoveFormat'],
        ],
        'height': 300,
        'width': '100%',
    },
}

# Configurações básicas do Django Allauth
SITE_ID = 1
AUTH_USER_MODEL = 'membros.Membro'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_ADAPTER = 'membros.adapters.CustomAccountAdapter'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'membros:painel'
LOGOUT_REDIRECT_URL = '/'

# Nova configuração para métodos de login (substitui ACCOUNT_AUTHENTICATION_METHOD)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}

# Nova configuração para campos obrigatórios no signup 
# (substitui ACCOUNT_EMAIL_REQUIRED e ACCOUNT_USERNAME_REQUIRED)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Verificação de e-mail obrigatória
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# Nova configuração para limite de tentativas de login
# (substitui ACCOUNT_LOGIN_ATTEMPTS_LIMIT e ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT)
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 tentativas por 5 minutos
}



# Configurações para confirmação e reset de senha
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_PASSWORD_RESET_EXPIRE_DAYS = 1

# Configurações adicionais úteis (opcionais)
ACCOUNT_PRESERVE_USERNAME_CASING = False  # Username em minúsculas
ACCOUNT_SESSION_REMEMBER = None  # Não lembrar sessão por padrão
ACCOUNT_LOGOUT_ON_GET = False  # Exigir POST para logout por segurança